from __future__ import annotations

from pathlib import Path
from random import Random
from typing import Iterable

from .models import Question

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _source(name: str) -> Path:
    return PROJECT_ROOT / name


QUESTION_BANK: tuple[Question, ...] = (
    Question(
        id="fault-1",
        topic="Reliability Metrics",
        prompt="Which metric measures the average operating time between failures for a repairable system?",
        choices=("MTBF", "MTTF", "MTTR", "RPO"),
        answer_index=0,
        explanation="MTBF is used for repairable systems and measures the average time between failures.",
        source_file=_source("fault_redundancy.txt"),
    ),
    Question(
        id="fault-2",
        topic="Reliability Metrics",
        prompt="Which metric is typically used for non-repairable components?",
        choices=("MTTR", "MTD", "MTTF", "WRT"),
        answer_index=2,
        explanation="MTTF is the expected operating lifetime before failure for a non-repairable component.",
        source_file=_source("fault_redundancy.txt"),
    ),
    Question(
        id="fault-3",
        topic="Reliability Metrics",
        prompt="What does MTTR measure?",
        choices=(
            "The time required to restore a system to full operation",
            "The maximum acceptable data loss",
            "The number of backup copies kept",
            "The average time between software updates",
        ),
        answer_index=0,
        explanation="MTTR measures how long it takes to correct a fault and restore service.",
        source_file=_source("fault_redundancy.txt"),
    ),
    Question(
        id="fault-4",
        topic="Reliability Metrics",
        prompt="A technician tracks a core switch that is repaired by replacing failed power supplies. Which metric is BEST for estimating the average operational interval before the next failure?",
        choices=("MTBF", "MTTF", "MTTR", "RTO"),
        answer_index=0,
        explanation="Because the switch is repairable, MTBF is the correct metric for the average interval between failures.",
        source_file=_source("fault_redundancy.txt"),
        difficulty="hard",
    ),
    Question(
        id="fault-5",
        topic="Reliability Metrics",
        prompt="A company buys optical transceivers that are discarded rather than repaired when they fail. Which metric should procurement use to estimate their expected service life?",
        choices=("MTTR", "MTBF", "MTTF", "RTO"),
        answer_index=2,
        explanation="MTTF is used for non-repairable components and represents expected lifetime before failure.",
        source_file=_source("fault_redundancy.txt"),
        difficulty="hard",
    ),
    Question(
        id="disc-1",
        topic="Discovery Protocols",
        prompt="Which discovery protocol is proprietary to Cisco devices?",
        choices=("LLDP", "CDP", "SNMP", "OSPF"),
        answer_index=1,
        explanation="CDP is Cisco proprietary, while LLDP is the open IEEE standard.",
        source_file=_source("cdp_lldp.txt"),
    ),
    Question(
        id="disc-2",
        topic="Discovery Protocols",
        prompt="Which multicast MAC address is used by LLDP?",
        choices=(
            "01:00:0c:cc:cc:cc",
            "ff:ff:ff:ff:ff:ff",
            "01:80:c2:00:00:0e",
            "01:00:5e:00:00:01",
        ),
        answer_index=2,
        explanation="LLDP uses the well-known multicast MAC address 01:80:c2:00:00:0e.",
        source_file=_source("cdp_lldp.txt"),
    ),
    Question(
        id="disc-3",
        topic="Discovery Protocols",
        prompt="Which command gives more detailed CDP information, such as software version and management addresses?",
        choices=(
            "show cdp",
            "show interfaces detail",
            "show cdp neighbors detail",
            "show lldp neighbors",
        ),
        answer_index=2,
        explanation="`show cdp neighbors detail` provides the detailed neighbor data.",
        source_file=_source("cdp_lldp.txt"),
    ),
    Question(
        id="disc-4",
        topic="Discovery Protocols",
        prompt="A network team manages Cisco and non-Cisco switches and wants one neighbor-discovery protocol to work across both vendors. Which protocol should the team enable?",
        choices=("CDP", "LLDP", "LLDP-MED", "PVST+"),
        answer_index=1,
        explanation="LLDP is the IEEE standards-based discovery protocol designed for multivendor environments.",
        source_file=_source("cdp_lldp.txt"),
        difficulty="hard",
    ),
    Question(
        id="disc-5",
        topic="Discovery Protocols",
        prompt="A technician runs `show cdp neighbors` and complains that the output does not include software version information. Which action is the BEST next step?",
        choices=(
            "Run `show cdp neighbors detail`",
            "Run `show cdp interface`",
            "Run `show cdp traffic`",
            "Run `show lldp neighbors detail`",
        ),
        answer_index=0,
        explanation="The detailed CDP command provides software version and management-address information that the summary command omits.",
        source_file=_source("cdp_lldp.txt"),
        difficulty="hard",
    ),
    Question(
        id="ipam-1",
        topic="IP Address Management",
        prompt="What does IPAM stand for?",
        choices=(
            "Internet Protocol Access Method",
            "IP Address Management",
            "Integrated Port Allocation Manager",
            "Internal Packet Address Mapping",
        ),
        answer_index=1,
        explanation="IPAM stands for IP Address Management.",
        source_file=_source("ipam.txt"),
    ),
    Question(
        id="ipam-2",
        topic="IP Address Management",
        prompt="Which issue can IPAM help identify?",
        choices=(
            "Overloaded DHCP scopes",
            "Damaged fiber transceivers",
            "Loopback adapter failures",
            "GPU overheating",
        ),
        answer_index=0,
        explanation="IPAM can identify overloaded DHCP scopes and help reclaim address space.",
        source_file=_source("ipam.txt"),
    ),
    Question(
        id="ipam-3",
        topic="IP Address Management",
        prompt="A company still tracks addressing in spreadsheets and keeps running out of public IP addresses because old assignments are not reclaimed. Which solution BEST addresses both problems?",
        choices=(
            "Deploy IPAM to correlate DHCP, DNS, and address usage centrally",
            "Increase DHCP lease durations and continue spreadsheet reconciliation",
            "Move public assignments to static reservations and track them manually",
            "Enable DNS scavenging and shorten DHCP leases to free addresses faster",
        ),
        answer_index=0,
        explanation="IPAM replaces manual tracking with centralized visibility into DHCP, DNS, and actual address usage.",
        source_file=_source("ipam.txt"),
        difficulty="hard",
    ),
    Question(
        id="agree-1",
        topic="Business Agreements",
        prompt="Which agreement defines the detailed terms under which a service is provided?",
        choices=("NDA", "MOU", "SLA", "BIA"),
        answer_index=2,
        explanation="An SLA defines service expectations, targets, and responsibilities.",
        source_file=_source("common_agreements_8_1_11.txt"),
    ),
    Question(
        id="agree-2",
        topic="Business Agreements",
        prompt="Which agreement is primarily used to protect sensitive information?",
        choices=("SLA", "NDA", "MOU", "DRP"),
        answer_index=1,
        explanation="An NDA defines how sensitive information may be used, stored, and shared.",
        source_file=_source("common_agreements_8_1_11.txt"),
    ),
    Question(
        id="agree-3",
        topic="Business Agreements",
        prompt="Which agreement is usually preliminary and not typically a binding contract?",
        choices=("MOU", "NDA", "SLA", "RPO"),
        answer_index=0,
        explanation="An MOU usually expresses intent to work together before a formal contract exists.",
        source_file=_source("common_agreements_8_1_11.txt"),
    ),
    Question(
        id="agree-4",
        topic="Business Agreements",
        prompt="Two companies want to document their intent to collaborate before negotiating a full contract, but they still want confidentiality expectations written down. Which document BEST fits?",
        choices=("NDA", "MOU", "SOW", "SLA"),
        answer_index=1,
        explanation="An MOU is the preliminary agreement used to express intent to work together and may include confidentiality clauses.",
        source_file=_source("common_agreements_8_1_11.txt"),
        difficulty="hard",
    ),
    Question(
        id="drp-1",
        topic="Continuity Planning",
        prompt="Which plan focuses on maintaining business operations during an adverse event?",
        choices=("DRP", "BCP", "BIA", "ITCP"),
        answer_index=1,
        explanation="A BCP keeps business operations running, while a DRP focuses on recovery from major incidents.",
        source_file=_source("drp.txt"),
    ),
    Question(
        id="drp-2",
        topic="Continuity Planning",
        prompt="What does a Business Impact Analysis identify?",
        choices=(
            "Cable routes and patch panel labels",
            "Mission-essential business functions and associated risks",
            "Only backup retention periods",
            "User password policies",
        ),
        answer_index=1,
        explanation="A BIA identifies critical business functions and the risks of being unable to perform them.",
        source_file=_source("drp.txt"),
    ),
    Question(
        id="drp-3",
        topic="Continuity Planning",
        prompt="What happens during a tabletop exercise?",
        choices=(
            "Teams discuss a hypothetical scenario",
            "Servers are physically destroyed",
            "Only auditors review firewall rules",
            "A replacement ISP is installed",
        ),
        answer_index=0,
        explanation="Tabletop exercises are discussion-based walk-throughs of a hypothetical incident.",
        source_file=_source("drp.txt"),
    ),
    Question(
        id="drp-4",
        topic="Continuity Planning",
        prompt="During recovery planning, department leads gather in a conference room, review a ransomware scenario, and talk through responsibilities without touching production systems. Which activity are they performing?",
        choices=("Validation test", "Tabletop exercise", "Simulation exercise", "Parallel test"),
        answer_index=1,
        explanation="A tabletop exercise is a discussion-based walkthrough of a hypothetical incident rather than a live technical failover.",
        source_file=_source("drp.txt"),
        difficulty="hard",
    ),
    Question(
        id="metric-1",
        topic="Recovery Metrics",
        prompt="Which formula must stay true when planning downtime targets?",
        choices=(
            "RPO + MTD <= MTTR",
            "RTO + WRT <= MTD",
            "MTBF + MTTF <= RPO",
            "WRT + BIA <= SLA",
        ),
        answer_index=1,
        explanation="The recovery target plus the work recovery time cannot exceed the maximum tolerable downtime.",
        source_file=_source("dr_metrics.txt"),
    ),
    Question(
        id="metric-2",
        topic="Recovery Metrics",
        prompt="What does RPO describe?",
        choices=(
            "How long a service can be offline",
            "Maximum acceptable data loss measured in time",
            "Time to replace network cabling",
            "Number of users affected by an outage",
        ),
        answer_index=1,
        explanation="RPO defines how much data loss is acceptable, usually expressed as time.",
        source_file=_source("dr_metrics.txt"),
    ),
    Question(
        id="metric-3",
        topic="Recovery Metrics",
        prompt="A payroll application has an MTD of 10 hours, and business managers say they need 3 hours after systems are restored to validate data and resume work. What is the LONGEST acceptable RTO?",
        choices=("6 hours", "7 hours", "8 hours", "9 hours"),
        answer_index=1,
        explanation="RTO plus WRT cannot exceed MTD, so 10 hours minus 3 hours leaves a maximum RTO of 7 hours.",
        source_file=_source("dr_metrics.txt"),
        difficulty="hard",
    ),
    Question(
        id="metric-4",
        topic="Recovery Metrics",
        prompt="A database has an RPO of four hours. If it is destroyed at 6:00 p.m., to which point must it be restored at minimum to stay within tolerance?",
        choices=("No older than 1:00 p.m.", "No older than 2:00 p.m.", "No older than 3:00 p.m.", "No older than 4:00 p.m."),
        answer_index=1,
        explanation="An RPO of four hours means the restored data can be at most four hours older than the incident time.",
        source_file=_source("dr_metrics.txt"),
        difficulty="hard",
    ),
    Question(
        id="diagram-1",
        topic="Network Documentation",
        prompt="Which type of diagram shows how cables are routed through a building?",
        choices=("Rack diagram", "Cable map or floor plan", "Wiring diagram", "Logical topology map"),
        answer_index=1,
        explanation="Cable maps and floor plans document where cables run between closets and work areas.",
        source_file=_source("physical_net_diagrams_8_1_8.txt"),
    ),
    Question(
        id="diagram-2",
        topic="Network Documentation",
        prompt="Which termination standards should be used consistently for Ethernet wiring?",
        choices=("RS-232 and RS-485", "BNC and F-type", "T568A or T568B", "SC or LC"),
        answer_index=2,
        explanation="Twisted-pair Ethernet termination should consistently follow either T568A or T568B.",
        source_file=_source("physical_net_diagrams_8_1_8.txt"),
    ),
    Question(
        id="diagram-3",
        topic="Network Documentation",
        prompt="What does a rack diagram record?",
        choices=(
            "The position of each appliance in the rack",
            "Only Layer 3 routing information",
            "The legal owner of each subnet",
            "The backup schedule for every server",
        ),
        answer_index=0,
        explanation="Rack diagrams show the physical placement of equipment in a rack.",
        source_file=_source("physical_net_diagrams_8_1_8.txt"),
    ),
    Question(
        id="diagram-4",
        topic="Network Documentation",
        prompt="In the port label `CB01-01A-D01`, what does `01A` represent?",
        choices=(
            "Building 1, floor A",
            "Telecommunications space A on floor 1",
            "Data port 1 on floor A",
            "Rack 1 in closet A",
        ),
        answer_index=1,
        explanation="The notes define `CB01-01A-D01` as Main Campus Building 01, telecommunications space A on floor 1, data port 1.",
        source_file=_source("physical_net_diagrams_8_1_8.txt"),
        difficulty="hard",
    ),
    Question(
        id="diagram-5",
        topic="Network Documentation",
        prompt="An installer needs documentation that shows the exact twisted-pair termination pattern inside an RJ45 jack. Which diagram type is the BEST fit?",
        choices=("Cable map", "Port schedule", "Wiring diagram", "Rack elevation"),
        answer_index=2,
        explanation="A wiring diagram documents how twisted pairs are terminated in an RJ45 jack or IDC.",
        source_file=_source("physical_net_diagrams_8_1_8.txt"),
        difficulty="hard",
    ),
    Question(
        id="life-1",
        topic="Decommissioning",
        prompt="Why is a factory reset alone not always sufficient when decommissioning a device?",
        choices=(
            "It voids the hardware warranty",
            "It may leave recoverable data remnants",
            "It changes the MAC address permanently",
            "It disables secure boot",
        ),
        answer_index=1,
        explanation="Factory reset may clear configuration, but stored data can still remain on the media.",
        source_file=_source("lifecycle_8_1_6.txt"),
    ),
    Question(
        id="life-2",
        topic="Decommissioning",
        prompt="Which storage media is less reliably sanitized by overwriting because of wear leveling?",
        choices=("Paper records", "Magnetic tape", "SSD and flash media", "Patch panels"),
        answer_index=2,
        explanation="Flash-based media use wear leveling, which makes direct overwriting less dependable.",
        source_file=_source("lifecycle_8_1_6.txt"),
    ),
    Question(
        id="life-3",
        topic="Decommissioning",
        prompt="What makes crypto erase effective on a self-encrypting drive?",
        choices=(
            "Reformatting the partition table",
            "Destroying the media encryption key",
            "Writing zeros to the boot sector",
            "Disabling SMART monitoring",
        ),
        answer_index=1,
        explanation="Once the media encryption key is destroyed, the encrypted data on the drive becomes unreadable.",
        source_file=_source("lifecycle_8_1_6.txt"),
    ),
    Question(
        id="life-4",
        topic="Decommissioning",
        prompt="Which Linux tool can issue the ATA Secure Erase command on supported drives?",
        choices=("tcpdump", "hdparm", "ethtool", "netstat"),
        answer_index=1,
        explanation="`hdparm` can be used to issue ATA Secure Erase on supported drives.",
        source_file=_source("lifecycle_8_1_6.txt"),
    ),
    Question(
        id="life-5",
        topic="Decommissioning",
        prompt="A company is returning leased self-encrypting SSDs and wants the fastest supported sanitization method that makes the stored data unreadable. Which action is BEST?",
        choices=(
            "Perform a cryptographic erase or vendor ISE operation",
            "Issue an ATA Secure Erase operation only",
            "Run repeated overwrite passes through the file system",
            "Delete partitions and recreate the volume",
        ),
        answer_index=0,
        explanation="On self-encrypting drives, crypto erase works by destroying the media encryption key, which immediately renders the data unreadable.",
        source_file=_source("lifecycle_8_1_6.txt"),
        difficulty="hard",
    ),
    Question(
        id="life-6",
        topic="Decommissioning",
        prompt="Why is repeated overwriting not the preferred sanitization guidance for modern SSDs?",
        choices=(
            "TRIM suppresses every write operation sent by the OS",
            "Wear leveling can remap writes away from the original flash cells",
            "Firmware-based sanitize functions work only on HDDs",
            "Self-encrypting drives always rewrite each NAND page directly",
        ),
        answer_index=1,
        explanation="Wear leveling can move writes around the drive, so overwriting does not guarantee that every physical location holding data is rewritten.",
        source_file=_source("lifecycle_8_1_6.txt"),
        difficulty="hard",
    ),
    Question(
        id="perf-1",
        topic="Performance Monitoring",
        prompt="What metric measures the actual amount of data transferred over a network link?",
        choices=("Bandwidth", "Throughput", "Storage", "MTTR"),
        answer_index=1,
        explanation="Throughput measures the actual amount of data transferred per unit of time.",
        source_file=_source("performance_monitoring_8_2_5.txt"),
    ),
    Question(
        id="perf-2",
        topic="Performance Monitoring",
        prompt="What is the purpose of establishing baseline metrics?",
        choices=(
            "To remove the need for future monitoring",
            "To compare later performance against a known state",
            "To encrypt management traffic",
            "To identify the rack position of a device",
        ),
        answer_index=1,
        explanation="Baseline metrics give you a known point of reference for measuring system responsiveness later.",
        source_file=_source("performance_monitoring_8_2_5.txt"),
    ),
    Question(
        id="perf-3",
        topic="Performance Monitoring",
        prompt="Which metric is usually expressed as a percentage of a link's rated bandwidth?",
        choices=("Utilization", "Storage", "Latency", "MTBF"),
        answer_index=0,
        explanation="Utilization is the percentage of the available bandwidth currently being used.",
        source_file=_source("performance_monitoring_8_2_5.txt"),
    ),
    Question(
        id="perf-4",
        topic="Performance Monitoring",
        prompt="An interface is rated for 1 Gbps, but current monitoring shows 400 Mbps of real traffic. Which metric does the 1 Gbps value represent?",
        choices=("Bandwidth", "Throughput", "Utilization", "Goodput"),
        answer_index=0,
        explanation="Bandwidth is the rated speed of the interface, while throughput is the real amount of data being transferred.",
        source_file=_source("performance_monitoring_8_2_5.txt"),
        difficulty="hard",
    ),
    Question(
        id="perf-5",
        topic="Performance Monitoring",
        prompt="A router shows sustained high CPU usage even though memory is stable. According to the notes, what could this indicate besides a need for an upgrade?",
        choices=(
            "A forwarding or traffic-processing problem",
            "An expired certificate chain",
            "A local storage-capacity problem",
            "An incorrect Ethernet wiring standard",
        ),
        answer_index=0,
        explanation="High CPU utilization can indicate a problem with network traffic, not just a capacity issue.",
        source_file=_source("performance_monitoring_8_2_5.txt"),
        difficulty="hard",
    ),
    Question(
        id="avail-1",
        topic="Availability Monitoring",
        prompt="What is the primary function of an availability monitor?",
        choices=(
            "To increase link speed",
            "To trigger an alarm for unscheduled downtime",
            "To replace baseline monitoring",
            "To rebuild the configuration automatically",
        ),
        answer_index=1,
        explanation="Availability monitors trigger alarms when a host or service becomes unavailable.",
        source_file=_source("availability_monitoring_8_2_6.txt"),
    ),
    Question(
        id="avail-2",
        topic="Availability Monitoring",
        prompt="Which HTTP status code would normally indicate that a monitored web resource is available?",
        choices=("404", "500", "302", "200"),
        answer_index=3,
        explanation="A normal `200` response indicates the resource is available.",
        source_file=_source("availability_monitoring_8_2_6.txt"),
    ),
    Question(
        id="avail-3",
        topic="Availability Monitoring",
        prompt="If a server hosting a service is overloaded, what action is the BEST one to consider first from the notes?",
        choices=(
            "Disable STP",
            "Throttle client connections",
            "Change the baseline configuration",
            "Reduce certificate expiration times",
        ),
        answer_index=1,
        explanation="The notes explicitly call out throttling connections when the server hosting a service is overloaded.",
        source_file=_source("availability_monitoring_8_2_6.txt"),
    ),
    Question(
        id="avail-4",
        topic="Availability Monitoring",
        prompt="Users cannot reach a service, and switch troubleshooting suggests STP messaging between switches is failing. Which issue is MOST likely causing the outage?",
        choices=("Broadcast storm", "Oversubscribed uplink", "Application thread deadlock", "Expired server certificate"),
        answer_index=0,
        explanation="The notes tie broadcast storms to bandwidth loss and STP communication problems.",
        source_file=_source("availability_monitoring_8_2_6.txt"),
        difficulty="hard",
    ),
    Question(
        id="config-1",
        topic="Configuration Monitoring",
        prompt="Which configuration state serves as the template for how a device should be configured?",
        choices=("Production configuration", "Golden configuration", "Backup configuration", "Running process table"),
        answer_index=1,
        explanation="The baseline or golden configuration is the template for the desired device state.",
        source_file=_source("configuration_monitor_8_2_7.txt"),
    ),
    Question(
        id="config-2",
        topic="Configuration Monitoring",
        prompt="What does a configuration monitor do when a device's production configuration changes?",
        choices=(
            "It disconnects the device immediately",
            "It updates the backup automatically",
            "It generates a log, alert, or alarm",
            "It forces a reboot into recovery mode",
        ),
        answer_index=2,
        explanation="A configuration monitor generates a log, alert, or alarm when the production configuration changes.",
        source_file=_source("configuration_monitor_8_2_7.txt"),
    ),
    Question(
        id="config-3",
        topic="Configuration Monitoring",
        prompt="Which configuration state is a point-in-time copy of the running or startup configuration?",
        choices=("Baseline configuration", "Backup configuration", "Running configuration", "Startup configuration"),
        answer_index=1,
        explanation="The backup configuration is the point-in-time copy of a running or startup config.",
        source_file=_source("configuration_monitor_8_2_7.txt"),
        difficulty="hard",
    ),
    Question(
        id="port-1",
        topic="Protocols and Ports",
        prompt="Which port numbers are associated with FTP in the CompTIA objectives?",
        choices=("20/21", "22", "23", "69"),
        answer_index=0,
        explanation="FTP uses ports 20 and 21.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-2",
        topic="Protocols and Ports",
        prompt="Which port does DNS use?",
        choices=("25", "53", "67", "123"),
        answer_index=1,
        explanation="DNS uses port 53.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-3",
        topic="Protocols and Ports",
        prompt="Which pair of ports is used by DHCP?",
        choices=("53/54", "67/68", "80/443", "161/162"),
        answer_index=1,
        explanation="DHCP uses ports 67 and 68.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-4",
        topic="Protocols and Ports",
        prompt="Which protocol commonly uses port 161 for queries and port 162 for traps?",
        choices=("SMTP", "SNMP", "SIP", "RDP"),
        answer_index=1,
        explanation="SNMP commonly uses 161 for queries and 162 for traps.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-5",
        topic="Protocols and Ports",
        prompt="Which secure protocol replaces Telnet for encrypted remote administration?",
        choices=("RDP on 3389", "SSH on 22", "SMB on 445", "Syslog on 514"),
        answer_index=1,
        explanation="SSH on port 22 is the secure replacement for Telnet on port 23.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-6",
        topic="Protocols and Ports",
        prompt="Which port should be opened for HTTPS traffic?",
        choices=("80", "389", "443", "636"),
        answer_index=2,
        explanation="HTTPS uses port 443.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-7",
        topic="Protocols and Ports",
        prompt="Which port does LDAPS use?",
        choices=("143", "389", "587", "636"),
        answer_index=3,
        explanation="LDAPS uses port 636, while LDAP uses 389.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-8",
        topic="Protocols and Ports",
        prompt="Which secure mail submission port is listed for SMTPS in the CompTIA objectives?",
        choices=("25", "110", "587", "995"),
        answer_index=2,
        explanation="The current CompTIA Network+ objectives list SMTPS on port 587.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-9",
        topic="Protocols and Ports",
        prompt="Which port is used by RDP?",
        choices=("445", "1433", "3389", "5061"),
        answer_index=2,
        explanation="RDP uses port 3389.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-10",
        topic="Protocols and Ports",
        prompt="Which port is commonly used by SMB?",
        choices=("161", "389", "445", "514"),
        answer_index=2,
        explanation="SMB uses port 445.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-11",
        topic="Protocols and Ports",
        prompt="Which protocol uses port 514?",
        choices=("Syslog", "DNS", "LDAP", "SFTP"),
        answer_index=0,
        explanation="Syslog uses port 514.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-12",
        topic="Protocols and Ports",
        prompt="Which port is associated with SQL Server in the notes?",
        choices=("123", "389", "1433", "3389"),
        answer_index=2,
        explanation="SQL Server commonly uses port 1433.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-13",
        topic="Protocols and Ports",
        prompt="Which port is commonly associated with IMAPS?",
        choices=("143", "443", "993", "995"),
        answer_index=2,
        explanation="IMAPS uses port 993.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-14",
        topic="Protocols and Ports",
        prompt="Which port is commonly associated with POP3S?",
        choices=("110", "143", "587", "995"),
        answer_index=3,
        explanation="POP3S uses port 995.",
        source_file=_source("protocols_ports_compTIA.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-15",
        topic="Protocols and Ports",
        prompt="A firewall rule should allow a secure file transfer service that uses the same port as SSH. Which port should be opened?",
        choices=("21", "22", "23", "69"),
        answer_index=1,
        explanation="SFTP uses port 22, the same port as SSH.",
        source_file=_source("protocols_ports_compTIA.txt"),
        difficulty="hard",
        tags=("ports", "secure"),
    ),
    Question(
        id="port-16",
        topic="Protocols and Ports",
        prompt="A web administrator wants to force encrypted access to the management portal. Which port should remain open to clients?",
        choices=("80", "443", "4443", "8443"),
        answer_index=1,
        explanation="Encrypted web traffic uses HTTPS on port 443.",
        source_file=_source("protocols_ports_compTIA.txt"),
        difficulty="hard",
        tags=("ports", "secure"),
    ),
    Question(
        id="port-17",
        topic="Protocols and Ports",
        prompt="Users need secure access to directory services. Which port should be permitted through the firewall?",
        choices=("389", "636", "993", "3269"),
        answer_index=1,
        explanation="LDAPS uses port 636 for encrypted directory traffic.",
        source_file=_source("protocols_ports_compTIA.txt"),
        difficulty="hard",
        tags=("ports", "secure"),
    ),
    Question(
        id="port-18",
        topic="Protocols and Ports",
        prompt="A VoIP engineer is troubleshooting encrypted signaling between SIP endpoints. Which port should the engineer check first?",
        choices=("5060", "5061", "5160", "8443"),
        answer_index=1,
        explanation="SIP over TLS commonly uses port 5061, while unencrypted SIP uses 5060.",
        source_file=_source("protocols_ports_compTIA.txt"),
        difficulty="hard",
        tags=("ports", "secure"),
    ),
    Question(
        id="route-1",
        topic="Routing Protocols",
        prompt="Which routing protocol is primarily used for routing between autonomous systems on the internet?",
        choices=("OSPF", "EIGRP", "BGP", "RIP"),
        answer_index=2,
        explanation="BGP is the routing protocol used between autonomous systems and listens on TCP port 179.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="route-2",
        topic="Routing Protocols",
        prompt="Which statement BEST describes BGP path-vector routing?",
        choices=(
            "It uses path information and policy to select routes",
            "It uses composite bandwidth and delay metrics to select routes",
            "It uses shortest-path cost calculations inside an area",
            "It selects routes strictly by hop count",
        ),
        answer_index=0,
        explanation="BGP is policy-driven and uses path information such as AS paths rather than simple hop count.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="route-3",
        topic="Routing Protocols",
        prompt="Which version of OSPF adds support for IPv6?",
        choices=("OSPFv1", "OSPFv2", "OSPFv3", "EIGRPv6"),
        answer_index=2,
        explanation="OSPFv3 is the version used for IPv6 support.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="route-4",
        topic="Routing Protocols",
        prompt="Which EIGRP algorithm is responsible for selecting the best path and a loop-free successor?",
        choices=("STP", "DUAL", "OSPF SPF", "RIPng"),
        answer_index=1,
        explanation="EIGRP uses DUAL to choose the best path and maintain a guaranteed loop-free successor.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="route-5",
        topic="Routing Protocols",
        prompt="Which EIGRP behavior helps reduce routing traffic by sending updates only when a change occurs?",
        choices=("Hello packets", "Partial routing updates", "Route summarization", "Administrative distance changes"),
        answer_index=1,
        explanation="EIGRP sends partial routing updates only when something changes, which reduces unnecessary traffic.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="net-1",
        topic="Network Fundamentals",
        prompt="In which network model do hosts commonly act as both clients and servers?",
        choices=("Client-server", "Peer-to-peer", "Hub-and-spoke", "Border gateway"),
        answer_index=1,
        explanation="Peer-to-peer networks are decentralized and let hosts act as both clients and servers.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="net-2",
        topic="Network Fundamentals",
        prompt="What is the primary advantage of a client-server network compared to a peer-to-peer network?",
        choices=(
            "Centralized management and security",
            "No need for dedicated servers",
            "Every host must provide its own resources",
            "It eliminates the need for applications",
        ),
        answer_index=0,
        explanation="Client-server networks centralize service delivery, management, and security on dedicated systems.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="net-3",
        topic="Network Fundamentals",
        prompt="What is an appliance in networking?",
        choices=(
            "A cable-testing tool",
            "A computer that performs a specific network role",
            "A switch port used for uplinks",
            "A non-routable IP address",
        ),
        answer_index=1,
        explanation="An appliance is a computer system dedicated to a specific network role and may be physical or virtual.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="net-4",
        topic="Network Fundamentals",
        prompt="Which topology is typically easiest to reconfigure and helps isolate faults automatically?",
        choices=("Bus", "Mesh", "Star", "Ring"),
        answer_index=2,
        explanation="A star topology is relatively easy to reconfigure and faults are usually isolated to individual links.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="net-5",
        topic="Network Fundamentals",
        prompt="What is a PDU in the context of encapsulation?",
        choices=(
            "A data unit handled at a specific protocol layer",
            "A frame header inserted only at Layer 2",
            "A control message used for route discovery",
            "A tag that identifies voice VLAN traffic",
        ),
        answer_index=0,
        explanation="A PDU is the data unit at a given protocol layer, including payload and any headers or trailers added there.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="tls-1",
        topic="OSI and TLS",
        prompt="Which statement BEST describes TLS?",
        choices=(
            "It is the modern secure replacement for SSL",
            "It replaced TCP on most networks",
            "It is a routing protocol for IPv6",
            "It is only used for web traffic",
        ),
        answer_index=0,
        explanation="TLS is the modern protocol used to secure communications and SSL is obsolete.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="tls-2",
        topic="OSI and TLS",
        prompt="In the OSI model, TLS responsibilities are usually associated with which layers?",
        choices=(
            "Physical and data link",
            "Network and transport",
            "Session and presentation",
            "Transport and physical",
        ),
        answer_index=2,
        explanation="TLS maps mainly to the session and presentation roles in the OSI model.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="tls-3",
        topic="OSI and TLS",
        prompt="What does Perfect Forward Secrecy help protect against?",
        choices=(
            "Previously captured encrypted traffic being exposed if a server key is later compromised",
            "Certificate revocation lists expiring before renewal",
            "Load balancer persistence exposing application cookies",
            "DNS MX records being spoofed during mail delivery",
        ),
        answer_index=0,
        explanation="PFS helps protect past sessions even if a long-term server key is later obtained by an attacker.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="time-1",
        topic="Time Synchronization",
        prompt="Which port and transport does NTP commonly use?",
        choices=("123/TCP", "123/UDP", "4460/TCP", "514/UDP"),
        answer_index=1,
        explanation="NTP commonly uses UDP port 123.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="time-2",
        topic="Time Synchronization",
        prompt="Which server obtains UTC time from a direct physical link to an accurate clock source?",
        choices=("Stratum 0", "Stratum 1", "Stratum 2", "Boundary clock"),
        answer_index=1,
        explanation="A stratum 1 server obtains highly accurate time from a direct clock source and serves other systems.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="time-3",
        topic="Time Synchronization",
        prompt="What is a key limitation of SNTP compared to full NTP implementations?",
        choices=(
            "It cannot use UDP",
            "It cannot act as a time source for other hosts",
            "It only works on Windows",
            "It requires a stratum 1 clock on every subnet",
        ),
        answer_index=1,
        explanation="A host that supports only SNTP is usually just a client and cannot serve as a time source for others.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="time-4",
        topic="Time Synchronization",
        prompt="If a system clock is only a few seconds off, which NTP correction method is generally appropriate according to the notes?",
        choices=("Slew", "Slam", "Stratum", "Boundary"),
        answer_index=0,
        explanation="The notes associate the slew method with smaller corrections and the slam method with larger ones.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="time-5",
        topic="Time Synchronization",
        prompt="Which protocol is preferred when nanosecond-level precision is required for workloads such as 5G or financial trading?",
        choices=("NTP", "NTS", "PTP", "SNTP"),
        answer_index=2,
        explanation="PTP is the IEEE 1588 protocol used where extremely precise time synchronization is required.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="svc-1",
        topic="File and Database Services",
        prompt="Which port is commonly used by SMB?",
        choices=("139", "1433", "445", "5432"),
        answer_index=2,
        explanation="Modern SMB commonly uses port 445.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="svc-2",
        topic="File and Database Services",
        prompt="Which port range is associated with legacy NetBIOS services?",
        choices=("135-137", "137-139", "139-141", "161-163"),
        answer_index=1,
        explanation="Legacy NetBIOS networking uses ports 137 through 139.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="svc-3",
        topic="File and Database Services",
        prompt="What is the main drawback of NAS noted in the study material?",
        choices=(
            "It cannot use RAID",
            "It shares bandwidth with other network applications",
            "It only works with Windows clients",
            "It cannot be accessed by IP address",
        ),
        answer_index=1,
        explanation="NAS traffic shares network bandwidth with other applications, which can create delays on congested networks.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="svc-4",
        topic="File and Database Services",
        prompt="Which database service commonly uses TCP port 3306?",
        choices=("Oracle", "Microsoft SQL Server", "MySQL or MariaDB", "PostgreSQL"),
        answer_index=2,
        explanation="MySQL and MariaDB commonly use TCP port 3306.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="svc-5",
        topic="File and Database Services",
        prompt="Which port is commonly associated with PostgreSQL?",
        choices=("1521", "3306", "445", "5432"),
        answer_index=3,
        explanation="PostgreSQL commonly uses TCP port 5432.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="mail-1",
        topic="Email and Voice Services",
        prompt="Which protocol is primarily used by clients to access and manage mail stored on a server?",
        choices=("SMTP", "IMAP", "SIP", "RTP"),
        answer_index=1,
        explanation="IMAP is the mail retrieval and mailbox-management protocol, while SMTP is used to send and relay mail.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="mail-2",
        topic="Email and Voice Services",
        prompt="Which SMTP port is typically reserved for relay between mail servers rather than end-user submission?",
        choices=("25", "143", "465", "587"),
        answer_index=0,
        explanation="Port 25 is normally used for server-to-server SMTP relay, while 465 and 587 are used for submission.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="mail-3",
        topic="Email and Voice Services",
        prompt="Which port is used for IMAPS?",
        choices=("110", "143", "587", "993"),
        answer_index=3,
        explanation="IMAPS uses port 993, while standard IMAP uses port 143.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="mail-4",
        topic="Email and Voice Services",
        prompt="Which statement about SMTP submission is MOST accurate?",
        choices=(
            "Port 465 is used for implicit TLS and 587 is commonly used for submission with STARTTLS",
            "Port 25 is preferred for end-user submission because it avoids TLS negotiation",
            "Port 587 is reserved only for server-to-server relay",
            "Port 993 is the preferred secure port for SMTP submission",
        ),
        answer_index=0,
        explanation="The notes distinguish port 465 for implicit TLS and port 587 for message submission using STARTTLS.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="voice-1",
        topic="Email and Voice Services",
        prompt="What is the role of a PBX in voice services?",
        choices=(
            "It encrypts all email traffic",
            "It acts as an automated switchboard for an organization's voice lines",
            "It provides database replication",
            "It replaces VLAN tagging on phones",
        ),
        answer_index=1,
        explanation="A PBX provides the switching and call-handling features for an organization's phone system.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="voice-2",
        topic="Email and Voice Services",
        prompt="Why do VoIP phones commonly use VLAN tagging?",
        choices=(
            "To segregate SIP and RTP traffic from normal data traffic",
            "To replace DSCP and other QoS markings on voice packets",
            "To convert VoIP calls into TDM channels before switching",
            "To avoid placing the VoIP edge behind a firewall",
        ),
        answer_index=0,
        explanation="Voice VLAN tagging helps separate SIP and RTP traffic from ordinary data traffic for better control and quality.",
        source_file=_source("earlier_content.txt"),
        difficulty="hard",
    ),
    Question(
        id="voice-3",
        topic="Email and Voice Services",
        prompt="Which function is commonly provided by real-time service protocols?",
        choices=(
            "Only file compression",
            "Session control",
            "Disk sanitization",
            "Port mirroring",
        ),
        answer_index=1,
        explanation="Real-time protocols can provide session control, data transfer, and QoS-related signaling.",
        source_file=_source("earlier_content.txt"),
    ),
    Question(
        id="port-19",
        topic="Protocols and Ports",
        prompt="Which port does BGP use?",
        choices=("53", "179", "389", "445"),
        answer_index=1,
        explanation="BGP commonly uses TCP port 179.",
        source_file=_source("earlier_content.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-20",
        topic="Protocols and Ports",
        prompt="Which secure protocol uses TCP port 4460 for key establishment?",
        choices=("LDAPS", "NTS", "HTTPS", "SMTPS"),
        answer_index=1,
        explanation="Network Time Security uses TCP port 4460 for NTS key establishment.",
        source_file=_source("earlier_content.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-21",
        topic="Protocols and Ports",
        prompt="Which port is commonly associated with Oracle Database?",
        choices=("1521", "3306", "5432", "5061"),
        answer_index=0,
        explanation="Oracle Database commonly uses TCP port 1521.",
        source_file=_source("earlier_content.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-22",
        topic="Protocols and Ports",
        prompt="Which port is commonly associated with MySQL or MariaDB?",
        choices=("1433", "1521", "3306", "5432"),
        answer_index=2,
        explanation="MySQL and MariaDB commonly use TCP port 3306.",
        source_file=_source("earlier_content.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-23",
        topic="Protocols and Ports",
        prompt="Which port is commonly associated with PostgreSQL?",
        choices=("25", "445", "993", "5432"),
        answer_index=3,
        explanation="PostgreSQL commonly uses TCP port 5432.",
        source_file=_source("earlier_content.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-24",
        topic="Protocols and Ports",
        prompt="Which port is the insecure default for IMAP?",
        choices=("110", "143", "465", "587"),
        answer_index=1,
        explanation="Standard IMAP uses port 143, while IMAPS uses 993.",
        source_file=_source("earlier_content.txt"),
        tags=("ports",),
    ),
    Question(
        id="port-25",
        topic="Protocols and Ports",
        prompt="Which port is commonly used for SMTP submission with implicit TLS?",
        choices=("25", "143", "465", "587"),
        answer_index=2,
        explanation="Port 465 is commonly used for SMTP submission with implicit TLS.",
        source_file=_source("earlier_content.txt"),
        tags=("ports", "secure"),
    ),
    Question(
        id="port-26",
        topic="Protocols and Ports",
        prompt="Which port is commonly used for SMTP submission with STARTTLS?",
        choices=("25", "465", "587", "993"),
        answer_index=2,
        explanation="Port 587 is commonly used for SMTP submission with explicit TLS via STARTTLS.",
        source_file=_source("earlier_content.txt"),
        tags=("ports", "secure"),
    ),
)


def _dedupe(values: Iterable[str]) -> tuple[str, ...]:
    seen: list[str] = []
    for value in values:
        if value not in seen:
            seen.append(value)
    return tuple(seen)


def available_topics() -> tuple[str, ...]:
    return _dedupe(question.topic for question in QUESTION_BANK)


def available_difficulties() -> tuple[str, ...]:
    return _dedupe(question.difficulty for question in QUESTION_BANK)


def available_tags() -> tuple[str, ...]:
    return _dedupe(tag for question in QUESTION_BANK for tag in question.tags)


def get_questions(
    *,
    topics: Iterable[str] | None = None,
    difficulties: Iterable[str] | None = None,
    required_tags: Iterable[str] | None = None,
    limit: int | None = None,
    shuffle: bool = True,
    seed: int | None = None,
) -> list[Question]:
    topic_filter = set(topics) if topics is not None else None
    difficulty_filter = set(difficulties) if difficulties is not None else None
    tag_filter = set(required_tags) if required_tags is not None else None

    filtered = [
        question
        for question in QUESTION_BANK
        if (topic_filter is None or question.topic in topic_filter)
        and (difficulty_filter is None or question.difficulty in difficulty_filter)
        and (tag_filter is None or tag_filter.issubset(set(question.tags)))
    ]

    if not filtered:
        return []

    if shuffle:
        rng = Random(seed)
        rng.shuffle(filtered)

    if limit is not None:
        return filtered[:limit]
    return filtered


def get_port_questions(
    *,
    secure_only: bool = False,
    difficulties: Iterable[str] | None = None,
    limit: int | None = None,
    shuffle: bool = True,
    seed: int | None = None,
) -> list[Question]:
    tags = ("ports", "secure") if secure_only else ("ports",)
    return get_questions(
        topics=("Protocols and Ports",),
        difficulties=difficulties,
        required_tags=tags,
        limit=limit,
        shuffle=shuffle,
        seed=seed,
    )
